config/routes.rb
UrlShortener::Application.routes.draw do

  get "urls/show"

  get "home/index"
  resources :user
  resources :urls
  devise_for :users
  
  root :to => "home#index"

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :user
  
  SHORT_URL_LENGTH = 6
  SHORT_URL_CHARS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
  
  def make_short_url
    shortened_url = ''    
    SHORT_URL_LENGTH.times { |i| shortened_url << SHORT_URL_CHARS[rand(SHORT_URL_CHARS.length)]}
    update_attribute(:short_url, shortened_url)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :urls, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(user)
    user_path(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def show
    @url = Url.find_by_short_url(params[:id])
    @url.counter += 1
    @url.save
    redirect_to  ("http://" + @url.long_url)
  end
  
  def create
    @url = current_user.urls.build(params[:url])
    @url.make_short_url
    if @url.save
      flash[:success] = "New url created!"
      redirect_to user_path(current_user)
    end
  end
  
  def destroy
    url = Url.find(params[:id])
    url.destroy
    redirect_to user_path(current_user)
  end
  
  def edit
    @url = Url.find(params[:id])
  end
  
  def update
    @url = Url.find(params[:id])
    if @url.update_attributes(params[:url])
      flash[:notice] = "Link updated"
    end
     redirect_to user_path(current_user)
  end
    
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
    @urls = @user.urls
    @url = Url.new
  end

  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <a class="brand" href="#">URL Shortener</a>
	          <div class="nav-collapse">
	            <ul class="nav">
		          <% if user_signed_in? %>
		          <li><%= link_to "Edit Password", edit_user_registration_path %></li>
		          <li><%= link_to "Sign out", destroy_user_session_path, :method => "Delete" %></li>
				<% else %>
					<li><%= link_to "Sign in", new_user_session_path %></li>
					<li><%= link_to "Sign up", new_user_registration_path %></li>
				<% end %>
	            </ul>
	          </div><!--/.nav-collapse -->
	        </div>
	      </div>
	    </div>
	

	
<div class="container">	
<br/>
	<br />
	<br />
<%= yield %>
<p class="notice"><%= notice %></p>

</div>

</body>
</html>

app/views/urls/edit.html.erb
<h1>Edit your Url</h1>

<%= form_for(@url) do |f| %>
  <div class="field"><br />
    <%= f.label :long_url %>
    <%= f.text_field :long_url %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/urls/show.html.erb
<%= request.env["HTTP_REFERER"].inspect %> 

app/views/user/index.html.erb
<h1>User#index</h1>
<%  @users.each do |user| %>
	<%=  user.email %>
	
	<% end %>

app/views/user/show.html.erb
<h1>Welcome, User <%= @user.id%></h1>
<!-- <%= @user.email %> -->
<p>

<br />	
<% if @user == current_user %>
Create new short url: <br />
<%= form_for @url do |f| %>
<div class="field">
    <%= f.text_field :long_url %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>
</p>
<%end%>


<table class="table table-bordered">
<% @urls.each do |url| %>
<tr><td>
<%= link_to "localhost:3000/urls/#{url.short_url}", ("http://" + url.long_url) %></td><td> <%= url.long_url%></td>
<% if @user == current_user %>
<td><%= url.counter%></td><td>
<%= link_to "edit", edit_url_path(url.id) %></td><td>
<%= link_to "delete", url, method: :delete, confirm: "Is you sure?" %></td>
<% end %></tr>
<% end %></table>